[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

; --- Memory: 16MB Flash + 8MB PSRAM (Octal) ---
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv

; --- USB: native USB Serial/JTAG ---
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
build_unflags =
    -DARDUINO_USB_MODE

; --- Libraries ---
lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git#3.0.12
    bblanchon/ArduinoJson@^7
    Bodmer/TJpg_Decoder

; --- Upload & Monitor ---
upload_speed = 921600
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
upload_port = COM6
monitor_port = COM6
